use mysql;
create user 'adcli'@'localhost' identified by "Daw2022@";
create database bdcli;
use bdcli;
create table if not exists tlcli(codi int primary key auto_increment not null, nom varchar(20) not null, cognoms varchar(50) not null, email varchar (50) not null);
grant select,insert,delete, update on bdcli.tlcli to 'adcli'@'localhost';
insert into tlcli (nom,cognoms,email) values("anna", "pÃ©rez pons", "app@gmail.com");
insert into tlcli (nom,cognoms,email) values("joan", "ramÃ­rez rocamora", "joan.ramirez@fje.edu");
insert into tlcli (nom,cognoms,email) values("pere", "masponts matadepera", "amasponts@protonamail.net");
show tables;
select * from tlcli;
show grants for 'adcli'@'localhost';